name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write # Needed for gh-pages deployment
  pages: write # Needed for GitHub Pages
  id-token: write # Needed for GitHub Pages authentication

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VITE_AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
      VITE_AUTH_SALT: ${{ secrets.AUTH_SALT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Create CNAME file
        run: echo 'kal.kot.li' > ./dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
